//
//  CourseDetailsWorker.swift
//  TestPatternsProject
//
//  Created by Олег Федоров on 30.12.2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import Foundation

class CourseDetailsWorker {
    func getImage(from imageURL: URL?) -> Data? {
        ImageManager.shared.fetchImageData(from: imageURL)
    }
    
    func getFavoriteStatus(for courseName: String) -> Bool {
        StorageManager.shared.getFavoriteStatus(for: courseName)
    }
    
    func setFavoriteStatus(for courseName: String, with status: Bool) {
        StorageManager.shared.setFavoritesStatus(for: courseName, with: status)
    }
}
