//
//  CourseDetailsInteractor.swift
//  TestPatternsProject
//
//  Created by Олег Федоров on 30.12.2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

protocol CourseDetailsBusinessLogic {
    var isFavorite: Bool { get}
    func provideCourseDetails(request: CourseDetailsRequest)
    func setFavoriteStatus()
}

protocol CourseDetailsDataStore {
    var course: Course? { get }
}

class CourseDetailsInteractor: CourseDetailsBusinessLogic, CourseDetailsDataStore {
    
    var presenter: CourseDetailsPresentationLogic?
    var worker: CourseDetailsWorker?
    
    var course: Course?
    var isFavorite: Bool = false
    
    func provideCourseDetails(request: CourseDetailsRequest) {
        course = request.course // delete after
        worker = CourseDetailsWorker()
        
        let imageData = worker?.getImage(from: course?.imageURL)
        isFavorite = worker?.getFavoriteStatus(for: course?.name ?? "") ?? false
        
        let response = CourseDetailsResponse(
            courseName: course?.name,
            numberOfLessons: course?.numberOfLessons,
            numberOfTests: course?.numberOfTests,
            imageData: imageData,
            isFavorite: isFavorite
        )
        presenter?.presentCourseDetails(response: response)
    }
    
    func setFavoriteStatus() {
        isFavorite.toggle()
        worker?.setFavoriteStatus(for: course?.name ?? "", with: isFavorite)
        
        let response = CourseStatusResponse(isFavorite: isFavorite)
        presenter?.presentFavoriteStatus(response: response)
    }
}
