//
//  CourseDetailsModels.swift
//  TestPatternsProject
//
//  Created by Олег Федоров on 30.12.2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import Foundation

typealias CourseDetailsRequest = CourseDetails.ShowDetails.Request
typealias CourseDetailsResponse = CourseDetails.ShowDetails.Response
typealias CourseDetailsViewModel = CourseDetails.ShowDetails.ViewModel

typealias CourseStatusResponse = CourseDetails.SetFavoriteStatus.Response
typealias CourseStatusViewModel = CourseDetails.SetFavoriteStatus.ViewModel

enum CourseDetails {
 
    // MARK: Use cases
    enum ShowDetails {
        struct Request {
            let course: Course
        }
        
        struct Response {
            let courseName: String?
            let numberOfLessons: Int?
            let numberOfTests: Int?
            let imageData: Data?
            let isFavorite: Bool
        }
        
        struct ViewModel {
            let courseName: String
            let numberOfLessons: String
            let numberOfTests: String
            let imageData: Data
            let isFavorite: Bool
        }
    }
    
    enum SetFavoriteStatus {
        struct Response {
            let isFavorite: Bool
        }
        
        struct ViewModel {
            let isFavorite: Bool
        }
    }
}
