//
//  CourseListModels.swift
//  TestPatternsProject
//
//  Created by Олег Федоров on 30.12.2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import Foundation


typealias CourseListResponse = CourseList.ShowCourses.Response
typealias CourseListViewModel = CourseList.ShowCourses.ViewModel
typealias CourseCellViewModel = CourseList.ShowCourses.ViewModel.CourceCellViewModel

protocol CourseCellViewModelProtocol {
    var height: Double { get }
    var courseName: String { get }
    var imageData: Data? { get }
    init(course: Course)
}

enum CourseList {

    // MARK: Use cases
    enum ShowCourses {
        struct Response {
            let courses: [Course]?
        }
        
        struct ViewModel {
            struct CourceCellViewModel: CourseCellViewModelProtocol {
                var height: Double {
                    100
                }
                
                var courseName: String {
                    course.name
                }
                
                var imageData: Data? {
                    ImageManager.shared.fetchImageData(from: course.imageURL)
                }
                
                private let course: Course
                
                init(course: Course) {
                    self.course = course
                }
            }
            
            let rows: [CourseCellViewModel]
        }
    }
}
