//
//  CourseListViewController.swift
//  TestPatternsProject
//
//  Created by Олег Федоров on 30.12.2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

private let reuseIdentifier = "CourseCell"

protocol CourseListDisplayLogic: AnyObject {
    func displayCourses(viewModel: CourseListViewModel)
}

class CourseListViewController: UITableViewController {
    
    // MARK: - Properties

    var interactor: CourseListBusinessLogic?
    var router: (NSObjectProtocol & CourseListRoutingLogic & CourseListDataPassing)?
    
    private var activityIndicator: UIActivityIndicatorView?
    private var rows: [CourseCellViewModel] = []
    
    // MARK: - View lifecycle
    override func viewDidLoad() {
        super.viewDidLoad()
        
        CourseListConfigurator.shared.configure(with: self)
        setupNavigationBar()
        configureTableView()
        activityIndicator = showActivityIndicator(in: view)
        getCourses()
    }
    
    // MARK: - Actions
    
    private func getCourses() {
        interactor?.fetchCourses()
    }
    
    // MARK: - Routing
    
//    override func prepare(for segue: UIStoryboardSegue, sender: Any?) {
//        if let scene = segue.identifier {
//            let selector = NSSelectorFromString("routeTo\(scene)WithSegue:")
//            if let router = router, router.responds(to: selector) {
//                router.perform(selector, with: segue)
//            }
//        }
//    }
    
    // MARK: - Helpers
    
    private func setupNavigationBar() {
        title = "Courses"
        navigationController?.navigationBar.prefersLargeTitles = true
        navigationController?.navigationBar.tintColor = .white
        
        let navBarAppearance = UINavigationBarAppearance()
        navBarAppearance.configureWithOpaqueBackground()
        
        navBarAppearance.backgroundColor = UIColor(red: 21/255, green: 101/255,
                                                   blue: 192/255, alpha: 194/255)
        
        navBarAppearance.titleTextAttributes = [.foregroundColor: UIColor.white]
        navBarAppearance.largeTitleTextAttributes = [.foregroundColor: UIColor.white]
        
        navigationController?.navigationBar.standardAppearance = navBarAppearance
        navigationController?.navigationBar.scrollEdgeAppearance = navBarAppearance
    }
    
    private func configureTableView() {
        tableView.register(CourseCell.self, forCellReuseIdentifier: reuseIdentifier)
    }
    
    private func showActivityIndicator(in view: UIView) -> UIActivityIndicatorView {
        let activityIndicator = UIActivityIndicatorView(style: .large)
        activityIndicator.color = .black
        activityIndicator.startAnimating()
        activityIndicator.hidesWhenStopped = true
        
        view.addSubview(activityIndicator)
        activityIndicator.centerX(inView: view,
                                  topAnchor: view.safeAreaLayoutGuide.topAnchor,
                                  paddingTop: 300)
        
        return activityIndicator
    }
}

// MARK: - UITableViewDataSource

extension CourseListViewController {
    override func tableView(_ tableView: UITableView, numberOfRowsInSection section: Int) -> Int {
        rows.count
    }
    
    override func tableView(_ tableView: UITableView,
                            cellForRowAt indexPath: IndexPath) -> UITableViewCell {
        let viewModelCell = rows[indexPath.row]
        
        let cell = tableView.dequeueReusableCell(
            withIdentifier: reuseIdentifier,
            for: indexPath
        ) as! CourseCell
        
        cell.viewModel = viewModelCell
        
        return cell
    }
}

// MARK: - UITableViewDelegate

extension CourseListViewController {
    override func tableView(_ tableView: UITableView,
                            didSelectRowAt indexPath: IndexPath) {
        tableView.deselectRow(at: indexPath, animated: true )
        router?.routeToCourseDetails()
//        let controller = CourseDetailsViewController()
//        controller.course = course
//
//        navigationController?.pushViewController(controller, animated: true)
    }
    
    override func tableView(_ tableView: UITableView,
                            heightForRowAt indexPath: IndexPath) -> CGFloat {
        CGFloat(rows[indexPath.row].height)
    }
}


extension CourseListViewController: CourseListDisplayLogic {
    func displayCourses(viewModel: CourseListViewModel) {
        rows = viewModel.rows
        DispatchQueue.main.async {
            self.tableView.reloadData()
            self.activityIndicator?.stopAnimating()
        }
    }
}
