//
//  CourseListInteractor.swift
//  TestPatternsProject
//
//  Created by Олег Федоров on 30.12.2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

protocol CourseListBusinessLogic {
    func doSomething(request: CourseList.Something.Request)
}

protocol CourseListDataStore {
    
}

class CourseListInteractor: CourseListBusinessLogic, CourseListDataStore {
    
    var presenter: CourseListPresentationLogic?
    
    func doSomething(request: CourseList.Something.Request) {
        
        let response = CourseList.Something.Response()
        presenter?.presentSomething(response: response)
    }
}
