//
//  CourseListRouter.swift
//  TestPatternsProject
//
//  Created by Олег Федоров on 30.12.2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

// логика перехода
@objc protocol CourseListRoutingLogic {
    func routeToCourseDetails()
}

// протокол определяет свойства, которые необходимо передать с одной сцены на другую
protocol CourseListDataPassing {
    var dataStore: CourseListDataStore? { get }
}

class CourseListRouter: NSObject, CourseListRoutingLogic, CourseListDataPassing {
    
    weak var viewController: CourseListViewController?
    var dataStore: CourseListDataStore?
    
    // MARK: Routing
    
    func routeToCourseDetails() {
        guard let viewController = viewController else { return }
        let destinationVC = CourseDetailsViewController()
        var destinationDS = destinationVC.router!.dataStore!
        guard let dataStore = dataStore else { return }
        
        passDataToCourseDetails(source: dataStore,
                                destination: &destinationDS)
        navigateToCourseDetails(source: viewController,
                                destination: destinationVC)
    }
    /*
    func routeToSomewhere(segue: UIStoryboardSegue?) {
        if let segue = segue {
            let destinationVC = segue.destination as! SomewhereViewController
            var destinationDS = destinationVC.router!.dataStore!
            passDataToSomewhere(source: dataStore!, destination: &destinationDS)
        } else {
            let storyboard = UIStoryboard(name: "Main", bundle: nil)
            let destinationVC = storyboard.instantiateViewController(withIdentifier: "SomewhereViewController") as! SomewhereViewController
            var destinationDS = destinationVC.router!.dataStore!
            passDataToSomewhere(source: dataStore!, destination: &destinationDS)
            navigateToSomewhere(source: viewController!, destination: destinationVC)
        }
    }
    */
    
    // MARK: Navigation
    func navigateToCourseDetails(source: CourseListViewController,
                                 destination: CourseDetailsViewController) {
        source.navigationController?.pushViewController(destination,
                                                        animated: true)
    }
    
    // MARK: Passing data
    func passDataToCourseDetails(source: CourseListDataStore,
                                 destination: inout CourseDetailsDataStore) {
        guard
            let indexPath = viewController?.tableView.indexPathForSelectedRow
        else { return }
        
        destination.course = source.courses[indexPath.row]
    }
}
